# Generated by Django 3.1.7 on 2021-03-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='subtitles',
            field=models.FilePathField(blank=True),
        ),
    ]
