# Generated by Django 3.1.7 on 2021-03-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210304_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FilePathField(blank=True, path='/code/storage'),
        ),
        migrations.AlterField(
            model_name='content',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FilePathField(blank=True, path='/code/storage'),
        ),
        migrations.AlterField(
            model_name='video',
            name='subtitles',
            field=models.FilePathField(blank=True, path='/code/storage'),
        ),
    ]
