# Generated by Django 3.1.7 on 2021-03-04 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210304_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.content'),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.content'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.content'),
        ),
    ]
