# Generated by Django 3.1.7 on 2021-03-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210304_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='app.content'),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='app.content'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='app.content'),
        ),
    ]
